version: '3.8'

services:
  # 🚀 Neo4j: Banco de grafos
  neo4j:
    image: neo4j:5.19
    container_name: neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password123}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    ports:
      - "7474:7474"   # Interface web
      - "7687:7687"   # Bolt (acesso por outras apps)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - theband-network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p ${NEO4J_PASSWORD:-password123} 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local

networks:
  theband-network:
    name: theband-network
    driver: bridge